# Generated by Django 5.0.6 on 2024-06-05 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
        ('article', '0003_articletagindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='advert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='advert.advert'),
        ),
    ]
